crypto/crypto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro.</description>
    <label>Mercado</label>
    <nameField>
        <label>Nome de Mercado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

crypto/crypto/force-app/main/default/objects/Mercado__c/fields/MoedaPrimaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaPrimaria__c</fullName>
    <description>Ativo primário, aquele que é comprado nas operações deste mercado.</description>
    <formula>LEFT(Name  ,FIND( &quot;/&quot;, Name )-1)</formula>
    <inlineHelpText>Ativo primário, aquele que é comprado nas operações deste mercado.</inlineHelpText>
    <label>Moeda Primária</label>
    <type>Text</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Mercado__c/fields/MoedaSecundaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaSecundaria__c</fullName>
    <description>Moeda Secundária é o ativo ao qual se vende neste mercado.</description>
    <formula>RIGHT(Name  ,LEN(Name )-FIND( &quot;/&quot;, Name ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Moeda Secundária é o ativo ao qual se vende neste mercado.</inlineHelpText>
    <label>Moeda Secundária</label>
    <type>Text</type>
</CustomField>

crypto/crypto/force-app/main/default/classes/BinanceAPI.cls
public class BinanceAPI {
    
    @AuraEnabled
    public static String getPrice(String mercadoId){
        Mercado__c mercado = [SELECT Id, MoedaPrimaria__c, MoedaSecundaria__c 
                              FROM Mercado__c
                              WHERE Id = :mercadoId];

        String pair = mercado.MoedaPrimaria__c + mercado.MoedaSecundaria__c;
        pair = pair.replace('USD', 'USDT');

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://api.binance.com/api/v3/ticker/price?symbol=' + pair);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if (response.getStatusCode() == 200) {
            SymbolPrice sp = (SymbolPrice)JSON.deserialize(response.getBody(), SymbolPrice.class);
            return sp.price;
        }else{
            return 'Erro ao acessar a API da Binance!';
        }
    }

    private Class SymbolPrice{
        String symbol;
        String price;
    }
}