crypto/crypto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro.</description>
    <label>Mercado</label>
    <nameField>
        <label>Nome de Mercado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

crypto/crypto/force-app/main/default/objects/Mercado__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <summarizedField>Ordem__c.QuantidadeP__c</summarizedField>
    <summaryForeignKey>Ordem__c.Mercado__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Número da  Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercado__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercado__c</referenceTo>
    <relationshipLabel>Ordem</relationshipLabel>
    <relationshipName>Ordem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da execução da Ordem.</description>
    <inlineHelpText>Status da execução da Ordem.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando</fullName>
                <default>true</default>
                <label>Aguardando</label>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Venda com lucro</fullName>
            </value>
            <value>
                <fullName>Venda com prejuízo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Identifica se a ordem é do tipo compra ou venda.</description>
    <inlineHelpText>Identifica se a ordem é do tipo compra ou venda.</inlineHelpText>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compra</fullName>
            </value>
            <value>
                <fullName>Venda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/classes/VFOrderController.cls
public class VFOrderController {
    
    public List<Ordem__c> ordemList {get; set;}
    public String currentValue {get; set;}
    public List<BinanceAPI.SymbolPrice> priceList {get; set;}
    public String html {get; set;}
    public DateTime currentDate {get; set;}
    
    public VFOrderController(){
        
    }

    public VFOrderController(ApexPages.StandardController controller){
        Mercado__c mercado = (Mercado__c) controller.getRecord(); 

        ordemList = [SELECT Id, Name,OperacaoMercado__c, Preco__c, toLabel(Tipo__c), Status__c, Quantidade__c, Total__c, Validade__c  
                     FROM Ordem__c 
                     WHERE Mercado__c =:mercado.Id
                    ];

        for(Ordem__c o : ordemList){
            o.Quantidade__c = o.Quantidade__c.setScale(6);
            o.Total__c = o.Total__c.setScale(6);
        }

        currentValue = BinanceAPI.getPrice(mercado.Id);
        priceList = BinanceAPI.getPrice();
        currentDate = DateTime.Now();
    }
}