crypto/crypto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro.</description>
    <label>Mercado</label>
    <nameField>
        <label>Nome de Mercado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

crypto/crypto/force-app/main/default/objects/Mercado__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Significa que o mercado está ativo para novas ordens.</description>
    <inlineHelpText>Significa que o mercado está ativo para novas ordens.</inlineHelpText>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Mercado__c/fields/CotacaoAtual__c.field-meta.xml
<CustomField>
    <fullName>CotacaoAtual__c</fullName>
    <label>Cotação Atual</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/classes/SchedulerGetPrecoHelper.cls
public with sharing class SchedulerGetPrecoHelper {
    public SchedulerGetPrecoHelper() 
    {}

    @future (callout=true)
    public static void AtualizaCotacaoAtualTodosMercadosAtivos()
    {
        Map<string,double> priceMap = new Map<string,double>();
        List<BinanceAPI.SymbolPrice> spList = BinanceAPI.getPrice();
        for(BinanceAPI.SymbolPrice sp : spList)
        {
            priceMap.put(sp.symbol, Double.valueof(sp.price));
        }
        List<Mercado__c> mercList = [SELECT name, ContinuousName__c FROM Mercado__c WHERE ativo__c = true AND ContinuousName__c in :priceMap.keyset()];
        for(Mercado__c mer : mercList)
        {
            mer.CotacaoAtual__c =priceMap.get(mer.ContinuousName__c);
        }
        update mercList;
    }
}