crypto/crypto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Número da  Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/classes/OrderDomainTest.cls
@istest
public class OrderDomainTest {
    
    @istest
    static void recalculaQuantidadeTest() 
    {
        //Criação do cenário de teste

        Ordem__c testOrdem = new Ordem__c(preco__c = 100, Total__c=1000);
        OrderDomain od = new OrderDomain(testOrdem);
        Test.startTest();
        od.recalculaQuantidade();
        Test.stopTest();
        System.assertEquals(10, od.order.quantidade__c, 'O recalculo de quantidade não está correto');
    }


    @istest
    static void recalculaQuantidadeSemPrecoTest() 
    {
        //Criação do cenário de teste

        Ordem__c testOrdem = new Ordem__c(preco__c = null, Total__c=1000);
        OrderDomain od = new OrderDomain(testOrdem);
        Test.startTest();
        od.recalculaQuantidade();
        Test.stopTest();
        System.assertEquals(1, od.order.getErrors().size(), 'O recalculo de quantidade não está correto');
    }

    @istest
    static void TestFodase() 
    {
        OrderDomain.aaa();
    }
}