crypto/crypto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Número da  Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/classes/OrderDomain.cls
public with sharing class OrderDomain {
    
    private Ordem__c order;

    public double getTotal()
    {
        return order.Total__c;
    }

    public OrderDomain(Ordem__c order) 
    {
        this.order = order;
    }

    public void recalculaTotal()
    {  
        if(order.preco__c != null && order.quantidade__c != null)
        {
            order.Total__c = order.quantidade__c * order.preco__c;
        }
        else 
        {
            order.adderror('Os valores de quantidade e preço não foram preenchidos.');
        }
    }

    public void recalculaQuantidade()
    {
        if(order.preco__c!=null && order.Total__c != null)
        {
            order.quantidade__c = order.Total__c  / order.preco__c;
        }
        else {
            order.adderror('Os valores de total e preço não foram preenchidos.');
        }
    }

    public boolean isFieldDifferent(Schema.sObjectField field, Ordem__c compareOrder)
    {
        return order.get(field) != compareOrder.get(field);
    }
}