crypto/crypto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Número da  Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/objects/Ordem__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

crypto/crypto/force-app/main/default/classes/OrderTriggerHandler.cls
public with sharing class OrderTriggerHandler extends TriggerHandler
{
    public OrderTriggerHandler() {}

    protected override void beforeInsert()
    {
        for (Ordem__c o : (List<Ordem__c>) trigger.new)
        {
            Ordem__c ordemFoda = o;
            /*CALCULO DO TOTAL*/
            if(ordemFoda.Total__c == null)
            {
                if(ordemFoda.preco__c != null && ordemFoda.quantidade__c != null)
                {
                    ordemFoda.Total__c = ordemFoda.quantidade__c * ordemFoda.preco__c;
                }
                else 
                {
                    ordemFoda.adderror('Os valores de quantidade e preço não foram preenchidos.');
                }
            }
            //CALCULO DA QUANTIDADE
            else {
                if(ordemFoda.preco__c!=null)
                {
                    ordemFoda.quantidade__c = ordemFoda.Total__c  / ordemFoda.preco__c;
                }
                else {
                    ordemFoda.adderror('Os valores de total e preço não foram preenchidos.');
                }
            }
        }

    }
    protected override void beforeUpdate()
    {
        for (Ordem__c o : (List<Ordem__c>) trigger.new)
        {
            Ordem__c ordemFoda = o;
            //Map<id,Ordem__c> oldMap;
            Ordem__c ordemMerda = (Ordem__c) trigger.oldMap.get(ordemFoda.id);
            //Erro de alteração de total
            if(ordemFoda.quantidade__c!= null && ordemFoda.preco__c!= null)
            {
                if(ordemMerda.Total__c != ordemFoda.Total__c  && ordemFoda.Total__c != (ordemFoda.quantidade__c * ordemFoda.preco__c))
                {
                    ordemFoda.adderror('O total não pode ser alterado manualmente depois que a ordem foi criada');
                }
                //Recalculo do total
                if(ordemMerda.quantidade__c != ordemFoda.quantidade__c || ordemMerda.preco__c != ordemFoda.preco__c)
                {
                    ordemFoda.total__c = ordemFoda.quantidade__c * ordemFoda.preco__c;
                }
            }
            else {
                ordemFoda.adderror('Os valores de quantidade e preço não foram preenchidos.');
            }

        }
    }

}